import abc
import threading
from collections.abc import Callable as Callable
from psycopg2.extras import ReplicationMessage
from queue import SimpleQueue
from typing import ParamSpec, TypeVar

PublisherMessage = str | bytes | bytearray | memoryview | object
QueueMessage = str | bytes
P = ParamSpec('P')
R = TypeVar('R')

def run_publisher_daemon(publisher: BasePublisher) -> None: ...
def ensure_running(func: Callable[P, R]) -> Callable[P, R]: ...

class MsgQueueMixin(metaclass=abc.ABCMeta):
    _MSG_QUEUE: SimpleQueue[PublisherMessage]
    def _get_message(self) -> QueueMessage | None: ...
    @property
    @abc.abstractmethod
    def msg_queue(self) -> SimpleQueue[PublisherMessage]: ...

class BasePublisher(metaclass=abc.ABCMeta):
    _lock: threading.Lock | None
    _running: bool
    _thread: threading.Thread | None
    _thread_lock: threading.Lock | None
    def _get_thread_lock(self) -> threading.Lock: ...
    @abc.abstractmethod
    def publish(self, msg: ReplicationMessage) -> None: ...
    @abc.abstractmethod
    def run(self) -> None: ...
    @abc.abstractmethod
    def stop(self) -> None: ...
    def is_running(self) -> bool: ...
    def set_running(self, value: bool) -> None: ...
    def start_worker(self) -> threading.Thread: ...
    def wait_stopped(self, timeout: float | None = None) -> bool: ...
