import abc
import threading
from _typeshed import Incomplete
from collections.abc import Callable as Callable
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from psycopg2.extras import ReplicationMessage
from queue import Queue
from typing import ParamSpec, TypeVar

logger: Incomplete
PublisherMessage = str | bytes | bytearray | memoryview | object
QueueMessage = str | bytes
P = ParamSpec('P')
R = TypeVar('R')

@dataclass
class PublishResult:
    accepted: bool
    dropped: bool = ...
    reason: str | None = ...

@dataclass
class PublisherMetrics:
    queue_capacity: int = ...
    dropped_count: int = ...
    publish_error_count: int = ...
    reconnect_count: int = ...
    last_error: str | None = ...
    last_success_at: datetime | None = ...

class PublisherState(str, Enum):
    IDLE = 'idle'
    STARTING = 'starting'
    RUNNING = 'running'
    DEGRADED = 'degraded'
    STOPPING = 'stopping'
    STOPPED = 'stopped'
    FAILED = 'failed'

def ensure_running(func: Callable[P, R]) -> Callable[P, R]: ...

class MsgQueueMixin(metaclass=abc.ABCMeta):
    _msg_queue: Queue[PublisherMessage]
    def _get_message(self, timeout: float | None=None) -> QueueMessage | None: ...
    @property
    @abc.abstractmethod
    def msg_queue(self) -> Queue[PublisherMessage]: ...

class BasePublisher(metaclass=abc.ABCMeta):
    _state: PublisherState
    _state_lock: Incomplete
    _thread: threading.Thread | None
    _thread_lock: Incomplete
    _stop_event: Incomplete
    _stopped: Incomplete
    _metrics: Incomplete
    def _drain_queue(self) -> None: ...
    def _queue_publish(self, payload: PublisherMessage) -> PublishResult: ...
    def __init__(self) -> None: ...
    @property
    def state(self) -> PublisherState: ...
    def set_state(self, value: PublisherState) -> None: ...
    @property
    def metrics(self) -> PublisherMetrics: ...
    def mark_success(self) -> None: ...
    def mark_error(self, exc: Exception | str, state: PublisherState = ...) -> None: ...
    def is_running(self) -> bool: ...
    def start(self) -> None: ...
    @property
    def requires_worker(self) -> bool: ...
    @abc.abstractmethod
    def publish(self, msg: ReplicationMessage) -> PublishResult: ...
    @abc.abstractmethod
    def run(self) -> None: ...
    def stop(self, drain: bool = False) -> None: ...
    def start_worker(self) -> threading.Thread: ...
    def wait_stopped(self, timeout: float | None = None) -> bool: ...
