from .base import BasePublisher as BasePublisher, MsgQueueMixin as MsgQueueMixin, PublishResult as PublishResult, PublisherMessage as PublisherMessage, PublisherState as PublisherState, QueueMessage as QueueMessage, ensure_running as ensure_running
from _typeshed import Incomplete
from kafka import KafkaProducer
from psycopg2.extras import ReplicationMessage
from queue import Queue

logger: Incomplete

class KafkaPublisher(BasePublisher, MsgQueueMixin):
    _PUBLISH_INTERVAL: float
    _kafka_config: dict[str, object]
    _producer: KafkaProducer | None
    _msg_queue: Queue[PublisherMessage]
    _sent: int
    def set_state(self, value: PublisherState) -> None: ...
    def mark_success(self) -> None: ...
    def mark_error(self, exc: Incomplete, state: PublisherState=PublisherState.DEGRADED) -> None: ...
    def is_running(self) -> bool: ...
    def start(self) -> None: ...
    def _drain_queue(self) -> None: ...
    def start_worker(self) -> Incomplete: ...
    def wait_stopped(self, timeout: float | None=None) -> bool: ...
    def _queue_publish(self, payload: PublisherMessage) -> PublishResult: ...
    def _get_message(self, timeout: float | None=None) -> QueueMessage | None: ...
    destination: Incomplete
    def __init__(self, destination: str, queue_size: int = 1000, **config: object) -> None: ...
    @property
    def producer(self) -> KafkaProducer: ...
    @property
    def msg_queue(self) -> Queue[PublisherMessage]: ...
    def publish_message(self, message: QueueMessage) -> None: ...
    def run(self) -> None: ...
    def stop(self, drain: bool = False) -> None: ...
    def flush(self, timeout: float | None = None) -> None: ...
    @ensure_running
    def publish(self, msg: ReplicationMessage) -> PublishResult: ...
