import pika
import threading
from .base import (
    BasePublisher as BasePublisher,
    MsgQueueMixin as MsgQueueMixin,
    PublisherMessage as PublisherMessage,
    ensure_running as ensure_running,
)
from _typeshed import Incomplete as Incomplete
from pika.exchange_type import ExchangeType as ExchangeType
from psycopg2.extras import ReplicationMessage
from queue import SimpleQueue
from typing import Any

logger: Incomplete

class RabbitPublisher(BasePublisher, MsgQueueMixin):
    msg_headers: dict[str, object]
    def __init__(
        self,
        amqp_url: str,
        exchange: str,
        queue: str,
        routing_key: str,
        exchange_type: ExchangeType = ...,
    ) -> None: ...
    @property
    def ready(self) -> threading.Event: ...
    @property
    def msg_queue(self) -> SimpleQueue[PublisherMessage]: ...
    def connect(self) -> pika.SelectConnection: ...
    def on_connection_open(self, _unused_connection: object) -> None: ...
    def on_connection_open_error(
        self, _unused_connection: object, err: Exception
    ) -> None: ...
    def on_connection_closed(
        self, _unused_connection: object, reason: Exception
    ) -> None: ...
    def open_channel(self) -> None: ...
    def on_channel_open(self, channel: Any) -> None: ...
    def add_on_channel_close_callback(self) -> None: ...
    def on_channel_closed(self, channel: Any, reason: Exception) -> None: ...
    def setup_exchange(self, exchange_name: str) -> None: ...
    def on_exchange_declareok(self, _unused_frame: object, userdata: str) -> None: ...
    def setup_queue(self, queue_name: str) -> None: ...
    def on_queue_declareok(self, _unused_frame: object) -> None: ...
    def on_bindok(self, _unused_frame: object) -> None: ...
    def start_publishing(self) -> None: ...
    def enable_delivery_confirmations(self) -> None: ...
    def on_delivery_confirmation(self, method_frame: Any) -> None: ...
    def schedule_next_message(self) -> None: ...
    def publish_message(self) -> None: ...
    def run(self) -> None: ...
    def stop(self) -> None: ...
    def close_channel(self) -> None: ...
    def close_connection(self) -> None: ...
    @ensure_running
    def publish(self, msg: ReplicationMessage) -> None: ...
