from .base import BasePublisher as BasePublisher
from _typeshed import Incomplete
from psycopg2.extras import ReplicationMessage

logger: Incomplete

class ShellPublisher(BasePublisher):
    _running: bool
    def is_running(self) -> bool: ...
    def set_running(self, value: bool) -> None: ...
    def _get_thread_lock(self) -> Incomplete: ...
    def start_worker(self) -> Incomplete: ...
    def wait_stopped(self, timeout: float | None=None) -> bool: ...
    def publish(self, msg: ReplicationMessage) -> None: ...
    def run(self) -> None: ...
    def stop(self) -> None: ...
