from .base import BasePublisher as BasePublisher, PublishResult as PublishResult, PublisherState as PublisherState
from _typeshed import Incomplete
from psycopg2.extras import ReplicationMessage

logger: Incomplete

class ShellPublisher(BasePublisher):
    def set_state(self, value: PublisherState) -> None: ...
    def mark_success(self) -> None: ...
    def mark_error(self, exc: Incomplete, state: PublisherState=PublisherState.DEGRADED) -> None: ...
    def is_running(self) -> bool: ...
    def _drain_queue(self) -> None: ...
    def start_worker(self) -> Incomplete: ...
    def wait_stopped(self, timeout: float | None=None) -> bool: ...
    def _queue_publish(self, payload: Incomplete) -> PublishResult: ...
    def __init__(self) -> None: ...
    @property
    def requires_worker(self) -> bool: ...
    def start(self) -> None: ...
    def publish(self, msg: ReplicationMessage) -> PublishResult: ...
    def run(self) -> None: ...
    def stop(self, drain: bool = False) -> None: ...
