import threading
from .consumers import ConsumerState as ConsumerState, WALConsumer as WALConsumer
from .publishers.base import BasePublisher as BasePublisher
from _typeshed import Incomplete
from dataclasses import dataclass
from enum import Enum
from psycopg2.extras import LogicalReplicationConnection

logger: Incomplete

class AppState(str, Enum):
    IDLE = 'idle'
    STARTING = 'starting'
    RUNNING = 'running'
    STOPPING = 'stopping'
    STOPPED = 'stopped'
    FAILED = 'failed'

@dataclass
class ConsumerHandle:
    consumer: WALConsumer
    thread: threading.Thread
    stop_event: threading.Event
    state: ConsumerState = ...
    last_error: str | None = ...
    def stop(self) -> None: ...
    def join(self, timeout: float | None = None) -> bool: ...

class PGWAL:
    def _run_consumer(self, handle: ConsumerHandle) -> None: ...
    dsn: Incomplete
    stop_event: Incomplete
    state: Incomplete
    consumer_handles: list[ConsumerHandle]
    publishers: list['BasePublisher']
    def __init__(self, dsn: dict[str, object]) -> None: ...
    def get_conn(self) -> LogicalReplicationConnection: ...
    def consume(self, consumer: WALConsumer) -> ConsumerHandle: ...
    def stop_publishers(self) -> None: ...
    def stop(self) -> None: ...
    def close(self) -> None: ...
    def status(self) -> dict[str, object]: ...
    def run(self) -> None: ...
