import threading
from .publishers.base import BasePublisher as BasePublisher
from _typeshed import Incomplete
from enum import Enum
from psycopg2.extras import ReplicationCursor, ReplicationMessage

logger: Incomplete

class ConsumerState(str, Enum):
    IDLE = 'idle'
    STARTING = 'starting'
    RUNNING = 'running'
    STOPPING = 'stopping'
    STOPPED = 'stopped'
    FAILED = 'failed'

class WALConsumer:
    _STATUS_INTERVAL: float
    _stop_event: Incomplete
    _state: ConsumerState
    _last_error: str | None
    def _publish_to_all(self, msg: 'ReplicationMessage') -> bool: ...
    def _consume(self, msg: 'ReplicationMessage') -> None: ...
    def _msg_n_consumed(self, cursor: 'ReplicationCursor') -> bool: ...
    def _get_cur_timeout(self, cursor: 'ReplicationCursor') -> float: ...
    def _wait_on_repl_cursor(self, cursor: 'ReplicationCursor') -> None: ...
    replication_slot: Incomplete
    replication_opts: Incomplete
    publishers: Incomplete
    def __init__(self, replication_slot: str, replication_opts: object, publishers: list['BasePublisher'] | None = None) -> None: ...
    @property
    def state(self) -> ConsumerState: ...
    def set_state(self, value: ConsumerState) -> None: ...
    @property
    def last_error(self) -> str | None: ...
    @property
    def stop_event(self) -> threading.Event: ...
    def stop(self) -> None: ...
    @property
    def output_plugin(self) -> str: ...
    def start_replication(self, cursor: ReplicationCursor) -> None: ...
    def consume_async(self, cursor: ReplicationCursor) -> None: ...
    def consume_sync(self, cursor: ReplicationCursor) -> None: ...
    def __call__(self, msg: ReplicationMessage) -> None: ...
