from .interface import WALReplicationOpts as WALReplicationOpts
from .publishers.base import BasePublisher as BasePublisher
from _typeshed import Incomplete as Incomplete
from psycopg2.extras import ReplicationCursor, ReplicationMessage

logger: Incomplete

class WALConsumer:
    replication_slot: Incomplete
    replication_opts: Incomplete
    publishers: Incomplete
    def __init__(
        self,
        replication_slot: str,
        replication_opts: WALReplicationOpts,
        publishers: list['BasePublisher'] | None = None,
    ) -> None: ...
    def set_consuming(self, value: bool) -> None: ...
    @property
    def consuming(self) -> bool: ...
    def stop(self) -> None: ...
    @property
    def output_plugin(self) -> str: ...
    def start_replication(self, cursor: ReplicationCursor) -> None: ...
    def consume_async(self, cursor: ReplicationCursor) -> None: ...
    def consume_sync(self, cursor: ReplicationCursor) -> None: ...
    def __call__(self, msg: ReplicationMessage) -> None: ...
