#!/usr/bin/env python3
"""Generate repository structure documentation."""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "docs" / "project-structure.md"
EXCLUDED_DIRS = {
    ".git",
    ".idea",
    ".local",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".tox",
    ".venv",
    "__pycache__",
    "venv",
}
EXCLUDED_FILES = {
    ".coverage",
    "pgwal-client.iml",
}


def is_included(path: Path) -> bool:
    """Return True when a path should appear in the generated tree."""
    rel = path.relative_to(ROOT)
    if any(part in EXCLUDED_DIRS for part in rel.parts):
        return False
    if path.name in EXCLUDED_FILES:
        return False
    if path.suffix in {".pyc", ".pyo"}:
        return False
    return True


def iter_children(path: Path) -> list[Path]:
    """Return sorted visible children for a path."""
    children = [child for child in path.iterdir() if is_included(child)]
    if path == OUTPUT.parent and OUTPUT not in children:
        children.append(OUTPUT)
    return sorted(children, key=lambda child: (not child.is_dir(), child.name))


def render_tree(path: Path, prefix: str = "") -> list[str]:
    """Render an ASCII tree for a directory."""
    children = iter_children(path)
    lines: list[str] = []
    for index, child in enumerate(children):
        connector = "`-- " if index == len(children) - 1 else "|-- "
        suffix = "/" if child.is_dir() else ""
        lines.append(f"{prefix}{connector}{child.name}{suffix}")
        if child.is_dir():
            extension = "    " if index == len(children) - 1 else "|   "
            lines.extend(render_tree(child, prefix + extension))
    return lines


def build_markdown() -> str:
    """Build the Markdown document."""
    repo_tree = "\n".join(["."] + render_tree(ROOT))
    module_tree = "\n".join(["pgwal/"] + render_tree(ROOT / "pgwal"))
    return "\n".join(
        [
            "# Project Structure",
            "",
            "Generated by `python scripts/update_project_structure.py`. Do not edit this file manually.",
            "",
            "## Repository Tree",
            "",
            "```text",
            repo_tree,
            "```",
            "",
            "## Module Tree",
            "",
            "```text",
            module_tree,
            "```",
            "",
        ]
    )


def main() -> None:
    """Write the generated documentation."""
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(build_markdown(), encoding="utf-8")


if __name__ == "__main__":
    main()
